"""Rung 8 -- null model: independent record marginals (S_null / D_MAX reference).

GENERATED by make_ladder_fixtures.py (POOL_SEED=50001, POOL_N=4000) - do not hand-edit.
"""
import numpy as np
import pandas as pd

MARG = {'driver': (5.018149193508187, 1.4721492192231516), 'stress': (1.2387302685592132, 1.2596487836000252), 'outcome': (36.63689472553232, 6.330600017086707)}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, 0.0, 10.0) if c == "driver" else v
    return pd.DataFrame(out)
