"""Rung 8 -- null: independent record marginals (S_null / D_MAX). GENERATED by build_and_certify.py (POOL_SEED=50001) - do not hand-edit."""
import numpy as np
import pandas as pd


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    return pd.DataFrame({"feedstock": rng.normal(5.982932259763762, 2.128407810343631, n),
                          "outcome": rng.normal(29.965275012854747, 5.931498204808006, n)})
