"""Rung 7 -- the digger's shippable (S_naive anchor, R=0): gaussian fit of
the archive yield marginal, blind to the feed. All the telemetry in the world
buys nothing beyond this for the deliverable. GENERATED by build_and_certify.py (POOL_SEED=50001) - do not hand-edit."""
import numpy as np
import pandas as pd


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    return pd.DataFrame({"gas_yield": rng.normal(21.57666173475082, 5.149087209722452, n)})
