"""Rung 3 - confounding_por_clase ablated (class_coef_dose=0), NO refit.

The visibility rung of the confounding operator (gate (ii) of the c_F sweep,
Decision Log v0.31): the world where the input assignment never depended on the
grade. Under do(dose) it is EXACT (the ablated pathway is exactly the one do()
replaces) - all of its loss is concentrated in the OBSERVATIONAL items, where
its dose marginal is wrong (mean 4.0 vs the confounded pool) and the
grade-input dependence is absent.

RATIONALE (rung 2 -> 3): rung 2 is mildly wrong EVERYWHERE; this rung is exactly
right on interventional items and structurally wrong on the observational quota.
No total order between them is guaranteed by construction (monotonia-por-eje,
ARCHITECTURE 13-L1): what IS required is losing >=3xCV vs truth under the
combined score - energy already sees a shifted dose marginal, so this operator's
visibility should NOT need the functional (the sharp-baseline expectation:
confounding-passes at c_F=0).

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260702, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

PARAMS = {'marker_sep': 2.2, 'marker_noise': 1.5, 'slope_a': 1.5, 'slope_b': -1.5, 'outcome_noise': 0.6, 'dose_base': 4.0, 'dose_noise': 1.2, 'class_coef_dose': 0.0}
DOSE_MIN, DOSE_MAX = 0.0, 10.0


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    mix_logit = float(regime.context.get("mix_logit", 0.0))
    z = rng.binomial(1, _sigmoid(mix_logit), n).astype(float)

    marker = p["marker_sep"] * z + rng.normal(0.0, p["marker_noise"], n)

    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = p["dose_base"] + p["class_coef_dose"] * z + rng.normal(0.0, p["dose_noise"], n)
        dose = np.clip(raw, DOSE_MIN, DOSE_MAX)

    effect = np.where(z > 0.5, p["slope_b"], p["slope_a"])
    outcome = effect * dose + rng.normal(0.0, p["outcome_noise"], n)

    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
