"""Rung 4 - innocent twin of confounding (machinery (b): ablation + refit).

Rival recipe (b) as build_standard_rivals derives it: operator removed AND free
params refit so the observational marginals match the corrupted pool - here the
dose_base absorbs the confounded pool's dose mean (5.220767606511047 vs the
truth's 4.0). It believes the historical input levels were just
'how the line runs', not grade-driven.

RATIONALE (rung 3 -> 4): the twin REPAIRS the dose marginal that rung 3 gets
wrong (its observational dose mean now matches the pool) but the repair is a
LIE: dose is shifted for every unit instead of for the type-B units, so the
grade-input dependence (and with it the marker-dose and outcome-dose joints)
is still wrong, and under do() it now runs a MIScalibrated assignment center
in observational-context predictions. The pair (3, 4) prices exactly what the
refit buys and what it cannot buy. For v1 the heterogeneity twin degenerates
to its pure ablation (the slope ablation does not touch the dose process ->
refit shift ~= 0; effect_dose leg inert) and is omitted as a duplicate
(Decision Log v0.33 addendum).

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260702, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

PARAMS = {'marker_sep': 2.2, 'marker_noise': 1.5, 'slope_a': 1.5, 'slope_b': -1.5, 'outcome_noise': 0.6, 'dose_base': 5.220767606511047, 'dose_noise': 1.2, 'class_coef_dose': 0.0}
DOSE_MIN, DOSE_MAX = 0.0, 10.0


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    mix_logit = float(regime.context.get("mix_logit", 0.0))
    z = rng.binomial(1, _sigmoid(mix_logit), n).astype(float)

    marker = p["marker_sep"] * z + rng.normal(0.0, p["marker_noise"], n)

    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = p["dose_base"] + p["class_coef_dose"] * z + rng.normal(0.0, p["dose_noise"], n)
        dose = np.clip(raw, DOSE_MIN, DOSE_MAX)

    effect = np.where(z > 0.5, p["slope_b"], p["slope_a"])
    outcome = effect * dose + rng.normal(0.0, p["outcome_noise"], n)

    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
