"""Rung 8 - null model: independent marginals of the observational pool.

RATIONALE (rung 7 -> 8): the null keeps only the historical marginals - it
destroys every dependency between columns AND every sensitivity to the regime
(under do(dose) it still samples dose from the pool marginal: the implicit
no-effect claim, priced on every item). Any fit to real data beats it on joint
structure; it is the "I know nothing" floor that anchors S_null, the D_MAX cap
and the crash semantics (crash pays strictly worse than this).

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260702, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

MARG = {'dose': (5.23205658716211, 1.7347954322606733), 'marker': (1.091050485903944, 1.8693124358131068), 'outcome': (-1.8427269391505283, 8.077254349774085)}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, 0.0, 10.0) if c == "dose" else v
    return pd.DataFrame(out)
