"""Rung 7 - naive generative fit: joint Gaussian of the corrupted pool.

Rival recipe (a), the S_naive anchor (R=0): "the data says what it seems to
say". A joint Gaussian of the single-composition observational pool, used
generatively; under do(dose) it samples (marker, outcome) from the
OBSERVATIONAL conditional given that dose.

RATIONALE (rung 6 -> 7): rung 6 gets every regime's first two moments exactly
right and fails only on shape; this rung's moments are frozen at the historical
composition and dragged through the observational conditional - under do() it
keeps the indication pattern randomization falsifies, and under composition
shifts (the out-of-record band) it does not move at all. It is the calibrated
"believe the record" floor of the normalization.

RATIONALE (rung 7 -> 8): see rung 8.

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260702, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

MU = np.array([5.2320565871620985, 1.091050485903944, -1.8427269391505274])
COV = np.array([[3.0095151917924956, 1.3690324576939419, -9.80268027536428], [1.3690324576939419, 3.4943289826855293, -8.758313861690283], [-9.80268027536428, -8.758313861690283, 65.24203783094433]])


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "dose" in regime.config:
        d = float(regime.config["dose"])
        mu_c = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_c = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        return pd.DataFrame(
            {"dose": np.full(n, d), "marker": draw[:, 0], "outcome": draw[:, 1]}
        )
    draw = rng.multivariate_normal(MU, COV, n)
    return pd.DataFrame(
        {
            "dose": np.clip(draw[:, 0], 0.0, 10.0),
            "marker": draw[:, 1],
            "outcome": draw[:, 2],
        }
    )
