"""Rung 8 -- null model: independent record marginals (S_null / D_MAX reference).

GENERATED by make_ladder_fixtures.py (POOL_SEED=50001, POOL_N=4000) - do not hand-edit.
"""
import numpy as np
import pandas as pd

MARG = {'driver': (5.078692296139803, 1.4991751619558673), 'signal': (-0.010416208010891185, 1.9149074356866036), 'outcome': (20.2365962308825, 10.29295621027424)}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, 0.0, 10.0) if c == "driver" else v
    return pd.DataFrame(out)
