"""Rung 7 -- naive joint Gaussian of the drifted, batched record (R=0).

Believes the record: the ramped-and-drifted slope IS the driver response.
GENERATED by make_ladder_fixtures.py (POOL_SEED=50001, POOL_N=4000) - do not hand-edit.
"""
import numpy as np
import pandas as pd

MU = np.array([5.078692296139803, -0.010416208010891185, 20.2365962308825])
COV = np.array([[2.2475261662254007, 0.036475309261471967, 10.179472727449971], [0.036475309261471967, 3.666870487247844, 5.678105904564767], [10.179472727449971, 5.678105904564767, 105.94494754662304]])


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "driver" in regime.config:
        d = float(regime.config["driver"])
        mu_c = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_c = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        return pd.DataFrame({"driver": np.full(n, d), "signal": draw[:, 0], "outcome": draw[:, 1]})
    draw = rng.multivariate_normal(MU, COV, n)
    return pd.DataFrame({"driver": np.clip(draw[:, 0], 0.0, 10.0), "signal": draw[:, 1], "outcome": draw[:, 2]})
