"""Rung 2 - truth with the four structural coefficients perturbed x1.15.

RATIONALE (rung 1 -> 2): a fixed 15% proportional error on grade separation,
both input slopes and the assignment strength produces a small but SYSTEMATIC
mismatch in every regime - in-support, out-of-record and observational alike -
while keeping every mechanism pathway intact (two grades, opposite signs,
confounded assignment). Expected strictly below the exact truth (whose only
mismatch is sampling noise) and above rungs that remove structure rather than
miscalibrate it.

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260702, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

PARAMS = {'marker_sep': 2.53, 'marker_noise': 1.5, 'slope_a': 1.725, 'slope_b': -1.725, 'outcome_noise': 0.6, 'dose_base': 4.0, 'dose_noise': 1.2, 'class_coef_dose': 2.875}
DOSE_MIN, DOSE_MAX = 0.0, 10.0


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    mix_logit = float(regime.context.get("mix_logit", 0.0))
    z = rng.binomial(1, _sigmoid(mix_logit), n).astype(float)

    marker = p["marker_sep"] * z + rng.normal(0.0, p["marker_noise"], n)

    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = p["dose_base"] + p["class_coef_dose"] * z + rng.normal(0.0, p["dose_noise"], n)
        dose = np.clip(raw, DOSE_MIN, DOSE_MAX)

    effect = np.where(z > 0.5, p["slope_b"], p["slope_a"])
    outcome = effect * dose + rng.normal(0.0, p["outcome_noise"], n)

    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
