"""Rung 5 - heterogeneidad_latente ablated (slope_b=+1.5), NO refit.

The visibility rung of the heterogeneity operator (gate (ii), the PRIMARY gate
of the c_F sweep): the homogeneous world where both grades respond with the
type-A slope. No sign flip -> no bimodal outcome under do(), no opposite tails,
no scrap mass where the truth has it.

RATIONALE (rung 4 -> 5): rungs 3-4 keep the heterogeneity and break assignment;
this rung keeps assignment and removes the heterogeneity itself - the structure
the case exists to reward. Note its moments are NOT matched to the truth (a
pure ablation shifts the outcome mean, which marginal energy distance does
see); the moment-matched competitor whose failure isolates what energy CANNOT
see is rung 6. Where the sharp c_F=0 baseline (heterogeneity-fails) actually
bites - this rung, rung 6, or both - is an empirical question the sweep's
baseline report answers per rung (Decision Log v0.31 (a)).

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260702, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

PARAMS = {'marker_sep': 2.2, 'marker_noise': 1.5, 'slope_a': 1.5, 'slope_b': 1.5, 'outcome_noise': 0.6, 'dose_base': 4.0, 'dose_noise': 1.2, 'class_coef_dose': 2.5}
DOSE_MIN, DOSE_MAX = 0.0, 10.0


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    mix_logit = float(regime.context.get("mix_logit", 0.0))
    z = rng.binomial(1, _sigmoid(mix_logit), n).astype(float)

    marker = p["marker_sep"] * z + rng.normal(0.0, p["marker_noise"], n)

    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = p["dose_base"] + p["class_coef_dose"] * z + rng.normal(0.0, p["dose_noise"], n)
        dose = np.clip(raw, DOSE_MIN, DOSE_MAX)

    effect = np.where(z > 0.5, p["slope_b"], p["slope_a"])
    outcome = effect * dose + rng.normal(0.0, p["outcome_noise"], n)

    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
