"""Rung 6 - moment-matched Gaussian oracle (DIAGNOSTIC rung, unimodal).

The strongest no-multimodality competitor: a Gaussian with the EXACT per-regime
mean and covariance of the truth, computed in closed form from PARAMS (mixture
moment algebra; the observational branch ignores dose clipping - declared
approximation, clip is ~4 sigma out at mix_logit=0). It fits any mean, variance
and heteroscedasticity perfectly; what it CANNOT represent is the two-cluster
joint. Under energy-alone it scored R=0.96 on Latent v0 (Decision Log v0.25) -
the blind spot the combined score exists to close.

RATIONALE (position): this rung is DIAGNOSTIC ("does the meter see?"), not a
degradation on any single axis: it answers gate (iii) - oracle strictly below
world.py by >=3xCV under the combined score - and has NO required rank among
the intermediate rungs (v0.31: where it lands is reported as data, never
gated). It operationalizes the Visibility certificate (ARCHITECTURE 7/13-L1).

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260702, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

PARAMS = {'marker_sep': 2.2, 'marker_noise': 1.5, 'slope_a': 1.5, 'slope_b': -1.5, 'outcome_noise': 0.6, 'dose_base': 4.0, 'dose_noise': 1.2, 'class_coef_dose': 2.5}
DOSE_MIN, DOSE_MAX = 0.0, 10.0


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def _mixture_moments(p_b, means, covs):
    """Exact mean/cov of a 2-component Gaussian mixture (weights 1-p_b, p_b)."""
    w = np.array([1.0 - p_b, p_b])
    m = w[0] * means[0] + w[1] * means[1]
    s = sum(
        w[k] * (covs[k] + np.outer(means[k] - m, means[k] - m)) for k in (0, 1)
    )
    return m, s


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    p_b = _sigmoid(float(regime.context.get("mix_logit", 0.0)))
    on2 = p["outcome_noise"] ** 2
    mn2 = p["marker_noise"] ** 2

    if "dose" in regime.config:
        d = float(regime.config["dose"])
        # per grade z: (marker, outcome) independent Gaussians at fixed dose
        means = [
            np.array([0.0, p["slope_a"] * d]),
            np.array([p["marker_sep"], p["slope_b"] * d]),
        ]
        covs = [np.diag([mn2, on2]), np.diag([mn2, on2])]
        m, s = _mixture_moments(p_b, means, covs)
        draw = rng.multivariate_normal(m, s, n)
        return pd.DataFrame(
            {"dose": np.full(n, d), "marker": draw[:, 0], "outcome": draw[:, 1]}
        )

    # observational: per grade z, (dose, marker, outcome) is Gaussian with
    # dose ~ N(base + coef*z, dn2), outcome = slope_z*dose + eps
    dn2 = p["dose_noise"] ** 2
    means, covs = [], []
    for z, slope in ((0.0, p["slope_a"]), (1.0, p["slope_b"])):
        mu_d = p["dose_base"] + p["class_coef_dose"] * z
        means.append(np.array([mu_d, p["marker_sep"] * z, slope * mu_d]))
        covs.append(
            np.array(
                [
                    [dn2, 0.0, slope * dn2],
                    [0.0, mn2, 0.0],
                    [slope * dn2, 0.0, slope**2 * dn2 + on2],
                ]
            )
        )
    m, s = _mixture_moments(p_b, means, covs)
    draw = rng.multivariate_normal(m, s, n)
    return pd.DataFrame(
        {
            "dose": np.clip(draw[:, 0], DOSE_MIN, DOSE_MAX),
            "marker": draw[:, 1],
            "outcome": draw[:, 2],
        }
    )
