"""Derived episode anchors for selection_bias_v0 (naive + null as CODE).

100% derived from the ROUTED pool (source_view: the filtered+noisy record --
the naive believes the corrupted view, v0.55 semantics). The callable-L1 and
certificates live in build_and_certify.py; these two fixtures exist because
episode scoring sandboxes the anchors as code (run_ladder convention:
second-to-last = naive, last = null -- names sort accordingly).

Run:  .venv/Scripts/python cases/selection_bias_v0/make_ladder_fixtures.py
"""

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
CASE = Path(__file__).parent

from wager.factory.case_loader import load_meta, load_world_sample  # noqa: E402
from wager.factory.derive_rivals import case_schema, observational_pool  # noqa: E402

POOL_SEED, POOL_N = 50001, 4000

HEADER = (
    "GENERATED by make_ladder_fixtures.py (ROUTED pool, POOL_SEED={s}, POOL_N={n})\n"
    "- do not hand-edit; regenerate to audit."
).format(s=POOL_SEED, n=POOL_N)


def main():
    meta = load_meta(CASE)
    schema = case_schema(meta)
    pool = observational_pool(load_world_sample(CASE), list(meta.episode.observe_sources.values())[0],
                              POOL_N, POOL_SEED)
    cols = list(schema.columns)
    mu = [float(v) for v in pool[cols].mean()]
    cov = [[float(v) for v in row] for row in pool[cols].cov().to_numpy()]
    marg = {c: (float(pool[c].mean()), float(pool[c].std())) for c in cols}
    d_idx = cols.index(schema.decision)

    naive = f'''"""Naive fit (S_naive anchor, rival a): joint Gaussian of the FILTERED+NOISY
record -- believes the corrupted view at face value (v0.55 semantics).

{HEADER}
"""
import numpy as np
import pandas as pd

COLS = {cols!r}
MU = np.array({mu!r})
COV = np.array({cov!r})
D_IDX = {d_idx}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "{schema.decision}" in regime.config:
        d = float(regime.config["{schema.decision}"])
        o_idx = [i for i in range(len(COLS)) if i != D_IDX]
        mu_c = MU[o_idx] + COV[o_idx, D_IDX] / COV[D_IDX, D_IDX] * (d - MU[D_IDX])
        cov_c = COV[np.ix_(o_idx, o_idx)] - np.outer(COV[o_idx, D_IDX], COV[D_IDX, o_idx]) / COV[D_IDX, D_IDX]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        out = {{"{schema.decision}": np.full(n, d)}}
        for k, j in enumerate(o_idx):
            out[COLS[j]] = draw[:, k]
    else:
        draw = rng.multivariate_normal(MU, COV, n)
        out = {{c: draw[:, i] for i, c in enumerate(COLS)}}
        out["{schema.decision}"] = np.clip(out["{schema.decision}"], {schema.lo!r}, {schema.hi!r})
    return pd.DataFrame(out)[COLS]
'''

    null = f'''"""Null model (S_null / D_MAX reference): independent marginals of the record.

{HEADER}
"""
import numpy as np
import pandas as pd

MARG = {marg!r}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {{}}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, {schema.lo!r}, {schema.hi!r}) if c == "{schema.decision}" else v
    return pd.DataFrame(out)
'''

    ladder = CASE / "ladder"
    ladder.mkdir(exist_ok=True)
    (ladder / "rung_7_naive_fit.py").write_text(naive, encoding="utf-8", newline="\n")
    (ladder / "rung_8_null.py").write_text(null, encoding="utf-8", newline="\n")
    print("wrote ladder/rung_7_naive_fit.py + rung_8_null.py (derived from routed pool)")


if __name__ == "__main__":
    main()
