"""Rung 8 -- null model: independent pool marginals (S_null / D_MAX reference).

GENERATED by anchors.null_marginals_code (POOL_SEED0=97001,
POOL_N=4000) -- do not hand-edit.
"""
import numpy as np
import pandas as pd

MARG = {'dose': (5.266816974327201, 1.7562729102737684), 'marker': (1.1063623014531498, 1.8516125640863743), 'outcome': (-1.9228328530913246, 8.120180073117117)}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, 0.0, 10.0) if c == "dose" else v
    return pd.DataFrame(out)
