"""truth_code -- the R=1 anchor of first_story_v0 (deliverable columns only).

Same mechanism and RNG call order as world.py; the era column t is drawn but
not returned. GENERATED by build_and_certify.py - do not hand-edit.
"""
import numpy as np
import pandas as pd

PARAMS = {'u_sd': 1.0, 'amb_base': 2.0, 'amb_drift': 6.0, 'amb_noise': 0.5, 'amb_center': 5.0, 'f_base': 6.0, 'grade_coef': 1.0, 'f_amb_coef': 0.9, 'f_noise': 0.9, 'y_base': 30.0, 'y_amb_coef': 2.5, 'u_coef': 3.0, 'y_noise': 2.0, 'grade_base': 5.0, 'grade_sd': 1.0}
KNOB_MIN, KNOB_MAX = 0.0, 10.0


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    u = rng.normal(0.0, p["u_sd"], n)
    if "humidity" in regime.config:
        ambient = np.full(n, float(regime.config["humidity"])) + rng.normal(0.0, p["amb_noise"], n)
    else:
        t = rng.uniform(0.0, 1.0, n)
        ambient = p["amb_base"] + p["amb_drift"] * t + rng.normal(0.0, p["amb_noise"], n)
    if "feedstock_grade" in regime.config:
        grade = np.full(n, float(regime.config["feedstock_grade"]))
    else:
        grade = np.clip(rng.normal(p["grade_base"], p["grade_sd"], n), KNOB_MIN, KNOB_MAX)
    feedstock = (p["f_base"] + p["grade_coef"] * (grade - p["grade_base"])
                 - p["f_amb_coef"] * (ambient - p["amb_center"])
                 + rng.normal(0.0, p["f_noise"], n))
    outcome = (p["y_base"] - p["y_amb_coef"] * (ambient - p["amb_center"])
               + p["u_coef"] * u + rng.normal(0.0, p["y_noise"], n))
    return pd.DataFrame({"feedstock": feedstock, "outcome": outcome})
