"""truth_code -- R=1 anchor of rabbit_hole_v2 (deliverable column only).
GENERATED by build_and_check.py - do not hand-edit."""
import numpy as np
import pandas as pd

AMPS = np.array([1.00, 0.72, 0.52, 0.38, 0.28, 0.20, 0.15, 0.11])
FREQS = np.array([0.35, 0.55, 0.80, 1.10, 1.50, 2.00, 2.70, 3.60])
PHASES = np.array([np.float64(2.981979982482674), np.float64(0.6602849868220143), np.float64(1.8108977599308578), np.float64(1.5114135892855078), np.float64(4.474063129570011), np.float64(3.356354845673419), np.float64(0.8001962294045084), np.float64(5.780280880697888)])
LP = {2: {'mu': 18.856145854693157, 'beta': 3.6670087799370004, 'c': 4.679091506360958, 's': 1.2671618818350645, 'gamma': -2.102895432310981, 'h': 6.16179452759871, 'w': 0.8832716971587838}, 3: {'mu': 21.88632522055272, 'beta': 3.7184399477351313, 'c': 5.570139930719477, 's': 1.2721872587070875, 'gamma': 2.8452196454550682, 'h': 6.562446809967431, 'w': 1.1233818123835075}, 4: {'mu': 21.3600767636306, 'beta': -3.4013072017568975, 'c': 6.138325709854971, 's': 1.493240297965626, 'gamma': -2.514161070733602, 'h': 8.289161241803974, 'w': 1.2390291070304102}, 5: {'mu': 14.801532468491486, 'beta': 2.702165347743869, 'c': 6.39636027300144, 's': 1.5013811933417969, 'gamma': 2.7711133142097646, 'h': 2.3824174260810698, 'w': 1.2426505757449888}}


def _g(name, d):
    if int(name) == 1:
        base = 12.0 + 16.0 * d ** 3 / (27.0 + d ** 3) - 4.0 / (1.0 + np.exp(-(d - 8.0) / 0.45))
        win = np.exp(-np.abs((d - 5.0) / 1.35) ** 8.0)
        local = np.zeros_like(d)
        for a, f, ph in zip(AMPS, FREQS, PHASES):
            local += a * np.sin(2.0 * np.pi * f * (d - 3.5) + ph)
        return base + win * local
    q = LP[int(name)]
    return (q["mu"] + q["beta"] * np.tanh((d - q["c"]) / q["s"])
            + q["gamma"] * np.exp(-((d - q["h"]) ** 2) / (2.0 * q["w"] ** 2)))


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    d = np.full(n, float(regime.config["driver"]))
    y = _g(int(regime.config["line"]), d) + rng.normal(0.0, 0.7, n)
    return pd.DataFrame({"outcome": y})
