"""Rung 7 -- the record-believer (S_naive anchor, R=0): grade moves the
reading, the reading moves quality; the hall does not exist. GENERATED by build_and_certify.py (POOL_SEED=50001) - do not hand-edit."""
import numpy as np
import pandas as pd


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    g = float(regime.config.get("feedstock_grade", 5.0))
    f = 5.982932259763762 + (g - 5.0) + rng.normal(0.0, 2.128407810343631, n)
    y = 20.149060829933454 + 1.640702878910563 * f + rng.normal(0.0, 4.794581790950177, n)
    return pd.DataFrame({"feedstock": f, "outcome": y})
