"""Rung 7 -- naive joint Gaussian of the historical record (R=0).

Believes the record: the record cluster IS the whole response surface.
GENERATED by make_ladder_fixtures.py (POOL_SEED=50001, POOL_N=4000) - do not hand-edit.
"""
import numpy as np
import pandas as pd

MU = np.array([4.563327518098527, -0.013583500331767919, 26.925252867420568])
COV = np.array([[1.4415136449709745, 0.025873207660224253, 3.5254533888423496], [0.025873207660224253, 3.2314594632648195, 3.925720403436418], [3.5254533888423496, 3.925720403436418, 34.1690470508788]])


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "driver" in regime.config:
        d = float(regime.config["driver"])
        mu_c = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_c = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        return pd.DataFrame({"driver": np.full(n, d), "signal": draw[:, 0], "outcome": draw[:, 1]})
    draw = rng.multivariate_normal(MU, COV, n)
    return pd.DataFrame({"driver": np.clip(draw[:, 0], 0.0, 10.0), "signal": draw[:, 1], "outcome": draw[:, 2]})
