"""truth_code -- the R=1 anchor of rabbit_hole_v0 (deliverable columns only).

Same mechanism and RNG call order as world.py; the telemetry block is drawn
but not returned. GENERATED by build_and_certify.py - do not hand-edit.
"""
import numpy as np
import pandas as pd


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "feed_setting" in regime.config:
        d = np.full(n, float(regime.config["feed_setting"]))
    else:
        d = rng.uniform(0.0, 10.0, n)
    dz = (d - 5.0) / 2.8867513459481287
    _proxy = 0.6 * dz + 0.8 * rng.normal(0.0, 1.0, n)
    _eb = rng.normal(0.0, 1.0, (5, n))
    _bc = rng.random(n)
    _bf = rng.random(n)
    y = (12.0 + 16.0 * d ** 3 / (27.0 + d ** 3)
         - 4.0 / (1.0 + np.exp(-(d - 8.0) / 0.45))
         + rng.normal(0.0, 1.5, n))
    return pd.DataFrame({"gas_yield": y})
