"""Episode anchor fixtures for survivorship_censor_v0 (naive + null as CODE).

Factory-side tooling (bootstrap exception, ADR 0033/0074 precedent). The naive
anchor is the record-believer: joint Gaussian of the SELECTED+CENSORED+NOISY
pool (routed through source_view, v0.55-1); the null keeps only its marginals.
Deterministic: regenerate to audit.

Run:  .venv/Scripts/python cases/survivorship_censor_v0/make_ladder_fixtures.py
"""

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
CASE = Path(__file__).parent
sys.path.insert(0, str(CASE))

import world  # noqa: E402

from wager.factory.case_loader import load_meta  # noqa: E402
from wager.harness.source_view import source_view  # noqa: E402

POOL_N, POOL_SEED = 4000, 50001


def main():
    meta = load_meta(CASE)
    source = list(meta.episode.observe_sources.values())[0]
    pool = source_view(world.sample, source, POOL_N, POOL_SEED)
    cols = list(world.COLUMNS)
    mu = [float(v) for v in pool[cols].mean().to_numpy()]
    cov = [[float(v) for v in row] for row in pool[cols].cov().to_numpy()]
    marg = {c: (float(pool[c].mean()), float(pool[c].std())) for c in cols}
    header = f"GENERATED by make_ladder_fixtures.py (POOL_SEED={POOL_SEED}, POOL_N={POOL_N}) - do not hand-edit."

    naive = f'''"""Rung 7 -- naive joint Gaussian of the screened+capped+noisy record (R=0).

Believes the record: the screened-era, bench-capped distribution IS production.
{header}
"""
import numpy as np
import pandas as pd

MU = np.array({mu!r})
COV = np.array({cov!r})


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "driver" in regime.config:
        d = float(regime.config["driver"])
        mu_c = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_c = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        return pd.DataFrame({{"driver": np.full(n, d), "stress": draw[:, 0], "outcome": draw[:, 1]}})
    draw = rng.multivariate_normal(MU, COV, n)
    return pd.DataFrame({{"driver": np.clip(draw[:, 0], 0.0, 10.0), "stress": draw[:, 1], "outcome": draw[:, 2]}})
'''
    null = f'''"""Rung 8 -- null model: independent record marginals (S_null / D_MAX reference).

{header}
"""
import numpy as np
import pandas as pd

MARG = {marg!r}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {{}}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, 0.0, 10.0) if c == "driver" else v
    return pd.DataFrame(out)
'''
    ladder = CASE / "ladder"
    ladder.mkdir(exist_ok=True)
    (ladder / "rung_7_naive_record.py").write_text(naive, encoding="utf-8", newline="\n")
    (ladder / "rung_8_null.py").write_text(null, encoding="utf-8", newline="\n")
    print("wrote ladder/rung_7_naive_record.py + rung_8_null.py")


if __name__ == "__main__":
    main()
