"""Rung 7 -- naive fit of the truncated noisy record (S_naive anchor, R=0).

Believes the ramp-up story: exponential growth, no ceiling, dispersion real.
GENERATED by build_and_certify.py (POOL_SEED=97001, POOL_N=400) - do not
hand-edit; regenerate to audit.
"""
import numpy as np
import pandas as pd

A, B, S_UNIT, S_READ = 0.019770981662764402, 0.44616974203024723, 0.4862662686884268, 1.0083882729013858


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    t = np.asarray(tuple(regime.context["t_grid"]), dtype=float)
    u = rng.normal(0.0, S_UNIT, n)[:, None]
    e = rng.normal(0.0, S_READ, (n, t.size))
    y = np.exp(A + B * t[None, :] + u + e)
    return pd.DataFrame({"unit_id": np.repeat(np.arange(n, dtype=float), t.size),
                          "t": np.tile(t, n), "y": y.ravel()})
