"""Rung 7 -- naive joint Gaussian of the screened+capped+noisy record (R=0).

Believes the record: the screened-era, bench-capped distribution IS production.
GENERATED by make_ladder_fixtures.py (POOL_SEED=50001, POOL_N=4000) - do not hand-edit.
"""
import numpy as np
import pandas as pd

MU = np.array([5.018149193508187, 1.2387302685592132, 36.63689472553232])
COV = np.array([[2.167223323659335, -0.00011799290568831591, 3.934955632939748], [-0.00011799290568831591, 1.5867150580250233, 2.691384178742249], [3.934955632939748, 2.691384178742249, 40.076496576338194]])


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "driver" in regime.config:
        d = float(regime.config["driver"])
        mu_c = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_c = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        return pd.DataFrame({"driver": np.full(n, d), "stress": draw[:, 0], "outcome": draw[:, 1]})
    draw = rng.multivariate_normal(MU, COV, n)
    return pd.DataFrame({"driver": np.clip(draw[:, 0], 0.0, 10.0), "stress": draw[:, 1], "outcome": draw[:, 2]})
