"""Rung 8 -- null model: record y-marginal, blind to time (S_null / D_MAX).

GENERATED by build_and_certify.py (POOL_SEED=98001, POOL_N=400) - do not
hand-edit; regenerate to audit.
"""
import numpy as np
import pandas as pd

MEAN, SD = 31.460606904021738, 17.302981044401715


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    t = np.asarray(tuple(regime.context["t_grid"]), dtype=float)
    y = rng.normal(MEAN, SD, (n, t.size))
    return pd.DataFrame({"unit_id": np.repeat(np.arange(n, dtype=float), t.size),
                          "t": np.tile(t, n), "y": y.ravel()})
