"""Naive fit (S_naive anchor, rival a): joint Gaussian of the FILTERED+NOISY
record -- believes the corrupted view at face value (v0.55 semantics).

GENERATED by make_ladder_fixtures.py (ROUTED pool, POOL_SEED=50001, POOL_N=4000)
- do not hand-edit; regenerate to audit.
"""
import numpy as np
import pandas as pd

COLS = ['driver', 'signal', 'outcome', 'ambient']
MU = np.array([5.015103976722816, 4.9353389181388705, 6.922607736726748, 0.016200951069419274])
COV = np.array([[8.375683613110613, 6.702300561416291, 10.10836543889904, 0.0138279204673188], [6.702300561416291, 5.9732162689436965, 7.717749483742134, 0.0022240825150082323], [10.10836543889904, 7.717749483742134, 15.022629319678192, 0.011754660372580545], [0.0138279204673188, 0.0022240825150082323, 0.011754660372580545, 1.02294140988546]])
D_IDX = 0


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "driver" in regime.config:
        d = float(regime.config["driver"])
        o_idx = [i for i in range(len(COLS)) if i != D_IDX]
        mu_c = MU[o_idx] + COV[o_idx, D_IDX] / COV[D_IDX, D_IDX] * (d - MU[D_IDX])
        cov_c = COV[np.ix_(o_idx, o_idx)] - np.outer(COV[o_idx, D_IDX], COV[D_IDX, o_idx]) / COV[D_IDX, D_IDX]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        out = {"driver": np.full(n, d)}
        for k, j in enumerate(o_idx):
            out[COLS[j]] = draw[:, k]
    else:
        draw = rng.multivariate_normal(MU, COV, n)
        out = {c: draw[:, i] for i, c in enumerate(COLS)}
        out["driver"] = np.clip(out["driver"], 0.0, 10.0)
    return pd.DataFrame(out)[COLS]
