"""overgen -- battery + anchors + the MINIMAL check (works for both poles:
reads world.POLE). Checks: the world runs; trivial hacks stay low; the PAIR
certificate holds (vice pole: juicio reaches and overgen pays; twin pole:
pooling wins and fragmenting pays; juicio wins BOTH). Pilot-z calibration is
printed (Codex r-overgen: subtle, ~0.8-1.5 sigma per point).

Run:  .venv/Scripts/python cases/<case>/build_and_check.py
"""

import json
import sys
from pathlib import Path
from types import SimpleNamespace

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
CASE = Path(__file__).parent
sys.path.insert(0, str(CASE))

import robots  # noqa: E402
import world  # noqa: E402

from wager.contracts import Battery, BatteryItem  # noqa: E402
from wager.contracts.world import Regime  # noqa: E402
from wager.harness.case_episode import build_world_server  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

LEVELS = [0.5, 1.8, 3.0, 4.2, 5.5, 6.8, 8.2, 9.5]
N_SEEDS = 3
NS = lambda c: SimpleNamespace(config=dict(c), context={}, horizon=None)  # noqa: E731


def build_battery():
    items, seeds = [], iter(range(78001, 78001 + 64))
    for name in world.LINES:
        for lvl in LEVELS:
            items.append(BatteryItem(
                weight=0.025, seed_world=next(seeds),
                regime=Regime(config={"line": name, "driver": lvl}, context={})))
    return Battery(items=items)


def write_truth_code():
    grid = np.round(np.arange(0.0, 10.001, 0.05), 3)
    parts = []
    for name in world.LINES:
        vals = world.g_curve(name, grid)
        xs = ", ".join(f"{v:g}" for v in grid)
        vs = ", ".join(f"{v:.4f}" for v in vals)
        parts.append(f'    {name}: (np.array([{xs}]), np.array([{vs}])),')
    tabs = "\n".join(parts)
    code = f'''"""truth_code -- R=1 anchor of {CASE.name} (dense tables of the true curves).
GENERATED by build_and_check.py - do not hand-edit."""
import numpy as np
import pandas as pd

T = {{
{tabs}
}}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    X, Y = T[int(regime.config["line"])]
    d = np.full(n, float(regime.config["driver"]))
    y = np.interp(d, X, Y) + rng.normal(0.0, {world.NOISE!r}, n)
    return pd.DataFrame({{"outcome": y}})
'''
    (CASE / "truth_code.py").write_text(code, encoding="utf-8", newline="\n")


def free_data_canonical():
    data = {}
    ov = world.sample(NS({}), 48, 61001)
    data[1] = (ov["driver"].to_numpy(float), ov["outcome"].to_numpy(float))
    for name in (2, 3, 4, 5):
        p = world.sample(NS({"__pilot": name}), 8, 61002 + name)
        data[name] = (p["driver"].to_numpy(float), p["outcome"].to_numpy(float))
    return data


def pilot_calibration(data):
    a, b, sd = robots._law_fit(*data[1])
    out = {}
    for name in (2, 3, 4, 5):
        z, _ = robots._pilot_z(a, b, data[name][0], data[name][1], sd)
        out[name] = round(z, 2)
    return out


def write_fixtures(data):
    tables = {1: robots._overview_table(*data[1])}
    sds = {1: 0.75}
    for name in (2, 3, 4, 5):
        tables[name] = robots._pchip_table(data[name][0], data[name][1])
        sds[name] = 0.75
    naive_code = robots._submission(tables, sds)
    pool = np.concatenate([
        world.sample(NS({"line": nm, "driver": dv}), 400, 61010 + i)["outcome"].to_numpy(float)
        for i, (nm, dv) in enumerate((n, d) for n in world.LINES for d in (2.0, 5.0, 8.0))])
    null_code = (f'"""Rung 8 -- null: collapsed variance at the pooled mean."""\n'
                 f"import numpy as np\nimport pandas as pd\n\n\n"
                 f"def model(regime, n, seed):\n"
                 f"    rng = np.random.default_rng(seed)\n"
                 f"    return pd.DataFrame({{'outcome': rng.normal({float(pool.mean())!r}, 0.01, n)}})\n")
    ladder = CASE / "ladder"
    ladder.mkdir(exist_ok=True)
    (ladder / "rung_7_naive_pilots.py").write_text(
        '"""Rung 7 -- the free shippable: overview + pilot fits only."""\n'
        + naive_code, encoding="utf-8", newline="\n")
    (ladder / "rung_8_null.py").write_text(null_code, encoding="utf-8", newline="\n")
    return pool


def main():
    battery = build_battery()
    battery.to_json_file(CASE / "battery.json")
    write_truth_code()
    data = free_data_canonical()
    pool = write_fixtures(data)

    checks: dict = {"pole": world.POLE, "pilot_z": pilot_calibration(data)}
    print(f"pole={world.POLE}  pilot z (canonical): {checks['pilot_z']}", flush=True)

    server = build_world_server(CASE, seed_offset=3)
    ok = server.submit((CASE / "truth_code.py").read_text(encoding="utf-8"))
    checks["contract_runs"] = bool(ok.accepted)
    checks["truth_R"] = round(server.result["R"], 4)

    hacks = {
        "constante_global": (f"import numpy as np\nimport pandas as pd\n\n"
                             f"def model(regime, n, seed):\n"
                             f"    rng = np.random.default_rng(seed)\n"
                             f"    return pd.DataFrame({{'outcome': rng.normal({float(pool.mean())!r}, {float(pool.std())!r}, n)}})\n"),
        "varianza_colapsada": (CASE / "ladder" / "rung_8_null.py").read_text(encoding="utf-8"),
        "ruido_x2": (CASE / "truth_code.py").read_text(encoding="utf-8").replace(
            f"{world.NOISE!r}, n", f"{2 * world.NOISE!r}, n"),
    }
    checks["hacks"] = {}
    for name, code in hacks.items():
        server = build_world_server(CASE, seed_offset=3)
        r = server.submit(code)
        checks["hacks"][name] = round(server.result["R"], 4) if r.accepted else None
        print(f"  hack {name}: R={checks['hacks'][name]}", flush=True)
    checks["hacks_low"] = (checks["hacks"]["constante_global"] <= 0.30
                           and checks["hacks"]["varianza_colapsada"] <= 0.30
                           and checks["hacks"]["ruido_x2"] <= 1.0 - 0.05)

    for name in ("juicio", "overgen", "fragment"):
        rs = []
        for k in range(N_SEEDS):
            res = robots.run_robot(CASE, name, seed_offset=20 + k)
            rs.append(res["R"])
            print(f"  robot {name} seed {20 + k}: R={res['R']:.4f} (left {res['left']:.0f})",
                  flush=True)
        checks[name] = [round(v, 4) for v in rs]

    j, o, f = (min(checks[n]) for n in ("juicio", "overgen", "fragment"))
    if world.POLE == "vice":
        checks["pair"] = {
            "juicio_reaches": j >= 0.75,
            "overgen_pays": round(min(a - b for a, b in zip(checks["juicio"], checks["overgen"])), 4),
            "overgen_pays_ok": min(a - b for a, b in zip(checks["juicio"], checks["overgen"])) >= 0.10,
        }
        checks["all"] = all([checks["contract_runs"], checks["hacks_low"],
                             checks["pair"]["juicio_reaches"], checks["pair"]["overgen_pays_ok"]])
    else:
        checks["pair"] = {
            "pool_wins": o >= 0.85 and j >= 0.85,
            "fragment_pays": round(min(a - b for a, b in zip(checks["juicio"], checks["fragment"])), 4),
            "fragment_pays_ok": min(a - b for a, b in zip(checks["juicio"], checks["fragment"])) >= 0.05,
            "juicio_matches_pool": abs(j - o) <= 0.05,
        }
        checks["all"] = all([checks["contract_runs"], checks["hacks_low"],
                             checks["pair"]["pool_wins"], checks["pair"]["fragment_pays_ok"],
                             checks["pair"]["juicio_matches_pool"]])

    print(json.dumps(checks, indent=2))
    (CASE / "check.json").write_text(json.dumps(checks, indent=2) + "\n", encoding="utf-8")
    print("-> battery.json + truth_code.py + ladder + check.json")


if __name__ == "__main__":
    main()
