"""truth_code -- the LEGAL R=1 anchor of mendel_subtypes_v2 (Decision Log v0.63).

Bayes posterior-predictive ceiling: posterior over the hidden lot mix from
regime.context["cal_window"] (declared grid x declared prior, marker mixture
likelihood), then EACH ROW samples its own mix ~ posterior (v0.63-1 verbatim;
never a per-table draw, never a mean/MAP plug-in). world.py itself is the
ILLEGAL player here (it reads the lot's hidden state) and is never scored as
an anchor. GENERATED by anchors.bayes_ceiling_code -- do not hand-edit.
"""
import numpy as np
import pandas as pd

PARAMS = {'marker_sep': 2.2, 'marker_noise': 1.5, 'slope_a': 1.5, 'slope_b': -1.5, 'outcome_noise': 0.6, 'dose_base': 4.0, 'dose_noise': 1.2, 'class_coef_dose': 2.5, 'lot_mix_sd': 1.8}
GRID = np.linspace(-5.4, 5.4, 61)
PRIOR_MU, PRIOR_SD = 0.0, 1.8
DOSE_MIN, DOSE_MAX = 0.0, 10.0


def _posterior_weights(window):
    p = PARAMS
    s = 1.0 / (1.0 + np.exp(-GRID))
    w = np.asarray(window, dtype=float)
    mn2 = p["marker_noise"] ** 2
    a = np.exp(-0.5 * (w[None, :] ** 2) / mn2)
    b = np.exp(-0.5 * ((w[None, :] - p["marker_sep"]) ** 2) / mn2)
    ll = np.log((1 - s)[:, None] * a + s[:, None] * b + 1e-300).sum(axis=1)
    logp = ll + (-0.5 * ((GRID - PRIOR_MU) / PRIOR_SD) ** 2)
    logp -= logp.max()
    wts = np.exp(logp)
    return wts / wts.sum()


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    wts = _posterior_weights(regime.context["cal_window"])
    s_row = 1.0 / (1.0 + np.exp(-rng.choice(GRID, size=n, p=wts)))
    z = (rng.random(n) < s_row).astype(float)
    marker = p["marker_sep"] * z + rng.normal(0.0, p["marker_noise"], n)
    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = p["dose_base"] + p["class_coef_dose"] * z + rng.normal(0.0, p["dose_noise"], n)
        dose = np.clip(raw, DOSE_MIN, DOSE_MAX)
    effect = np.where(z > 0.5, p["slope_b"], p["slope_a"])
    outcome = effect * dose + rng.normal(0.0, p["outcome_noise"], n)
    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
