"""mendel_subtypes_v2 - hidden per-lot mix, inferred from a calibration window.

The truth of the case. Server-side only: the agent never sees this file.

THE REAL CASE of the Latent triptych (v0=clean proxy, v1=declared dial,
v2=hidden state; ARCHITECTURE §10.1, Decision Log v0.47). The lot's grade
composition (`mix_logit`) is a HIDDEN per-lot parameter: sampled from a prior
the agent never sees, absent from the control surface AND from model()'s
inputs. What each evaluation regime carries instead is a small UNLABELED
calibration window: n_cal sensor readings from that lot, generated by the
world from the WORLD-SIDE seed (CRN: the same window reaches the submission,
the anchors and every rival).

Mechanism per lot (same invariant per-grade laws as v1):

    mix_logit ~ N(0, lot_mix_sd)          # HIDDEN; prior range exceeds the
                                          # historical record (lot_mix_sd 1.8)
    z      ~ Bernoulli(sigmoid(mix_logit))
    marker := marker_sep * z + N(0, marker_noise)     # noisy reading (v1's law)
    dose   := clip(dose_base + class_coef_dose*z + N(0,dose_noise), 0, 10)
              (replaced by regime.config["dose"] under do())
    effect := slope_a if z==0 else slope_b
    outcome:= effect * dose + N(0, outcome_noise)

Seeds (CRN discipline, §10.1-b): the LOT identity derives from the sampling
seed via a fixed tag (lot_mix(seed)); row noise uses the seed itself. The
truth side calls sample(regime, n, seed_world) -> lot = lot_mix(seed_world);
the window handed to model/rivals is make_window(seed_world, n_cal) -> SAME
lot. A submission that echoes world.py cannot recover the lot from ITS
model-side seed (derive_seed(seed_world, j) != seed_world): world.py is NOT
the ceiling here -- the R=1 anchor is the Bayes-adaptive truth (§10.1-e,
GATE: anchor spec under artifact-level review before wiring).
"""

import numpy as np
import pandas as pd

COLUMNS = ["dose", "marker", "outcome"]

PARAMS = {
    "marker_sep": 2.2,
    "marker_noise": 1.5,
    "slope_a": 1.5,
    "slope_b": -1.5,
    "outcome_noise": 0.6,
    "dose_base": 4.0,
    "dose_noise": 1.2,
    "class_coef_dose": 2.5,
    "lot_mix_sd": 1.8,       # hidden-prior width; exceeds the historical record
}
DOSE_MIN, DOSE_MAX = 0.0, 10.0
_LOT_TAG = 424243            # lot-identity rng tag (disjoint from scoring reps)
_WINDOW_TAG = 424244         # calibration-window rng tag

WINDOW_KEY = "cal_window"    # regime.context key carrying the unlabeled readings
WINDOW_PROTOCOL = "v2.window.1"  # versioned (§10.1-b)


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def lot_mix(seed: int) -> float:
    """The lot's hidden mix, derived from the WORLD-side seed (one lot per
    battery item / episode draw)."""
    return float(np.random.default_rng((seed, _LOT_TAG)).normal(0.0, PARAMS["lot_mix_sd"]))


def make_window(seed: int, n_cal: int) -> tuple:
    """The calibration window for the lot of `seed`: n_cal UNLABELED marker
    readings, same marker law as the mechanism. Deterministic in (seed, n_cal);
    generated ONCE per item and shared (CRN) by submission, anchors, rivals."""
    rng = np.random.default_rng((seed, _WINDOW_TAG))
    mix = lot_mix(seed)
    z = rng.binomial(1, _sigmoid(mix), n_cal).astype(float)
    return tuple(float(v) for v in PARAMS["marker_sep"] * z
                 + rng.normal(0.0, PARAMS["marker_noise"], n_cal))


def mechanism(params, regime, n, seed):
    p = params
    rng = np.random.default_rng(seed)
    mix = lot_mix(seed)  # HIDDEN: never read from regime
    z = rng.binomial(1, _sigmoid(mix), n).astype(float)

    marker = p["marker_sep"] * z + rng.normal(0.0, p["marker_noise"], n)
    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = p["dose_base"] + p["class_coef_dose"] * z + rng.normal(0.0, p["dose_noise"], n)
        dose = np.clip(raw, DOSE_MIN, DOSE_MAX)
    effect = np.where(z > 0.5, p["slope_b"], p["slope_a"])
    outcome = effect * dose + rng.normal(0.0, p["outcome_noise"], n)
    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})


def sample(regime, n, seed):
    return mechanism(PARAMS, regime, n, seed)


model = sample
