"""Rung 7 -- naive pooled fit of the historical record (S_naive anchor, R=0).

Joint Gaussian of the pooled multi-lot record; believes the historical record,
ignores the calibration window entirely. GENERATED by anchors.pooled_naive_code
(POOL_SEED0=97001, POOL_N=4000) -- do not hand-edit.
"""
import numpy as np
import pandas as pd

MU = np.array([5.266816974327201, 1.1063623014531498, -1.9228328530913246])
COV = np.array([[3.0844945353614923, 1.4585223713559812, -10.050768280594585], [1.4585223713559812, 3.428469087482518, -8.73308364347822], [-10.050768280594585, -8.73308364347822, 65.93732441984835]])


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "dose" in regime.config:
        d = float(regime.config["dose"])
        mu_c = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_c = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        return pd.DataFrame({"dose": np.full(n, d), "marker": draw[:, 0], "outcome": draw[:, 1]})
    draw = rng.multivariate_normal(MU, COV, n)
    return pd.DataFrame({"dose": np.clip(draw[:, 0], 0.0, 10.0), "marker": draw[:, 1], "outcome": draw[:, 2]})
