"""Deterministic generator of the mendel_subtypes_v1 ladder fixtures (rungs 2-8).

Factory-side tooling (bootstrap exception, Decision Log v0.33 addendum: hand-built
ladder expires with automatic rival derivation, same rule as the dummy's).

Composition (Decision Log v0.33, direccion de Lucas -- full, not thinned):
  rung 1  world.py exact                      (automatic, R=1 anchor)
  rung 2  params perturbed x1.15              (all four structural coefficients)
  rung 3  ablate confounding_por_clase        (pure ablation FROM meta, no refit)
  rung 4  innocent twin of confounding        (machinery (b): ablation + dose_base
                                               refit to the pool marginal -- differs
                                               from rung 3; the heterogeneity twin
                                               is ~= its pure ablation for v1 and is
                                               omitted as a duplicate, registered)
  rung 5  ablate heterogeneidad_latente       (pure ablation FROM meta, no refit)
  rung 6  moment-matched Gaussian oracle      (DIAGNOSTIC rung: exact per-regime
                                               mean+cov, unimodal; no required rank
                                               among intermediates -- only
                                               oracle < truth is gated, v0.31 (iii))
  rung 7  naive fit (joint Gaussian of pool)  (anchor S_naive, R=0)
  rung 8  null (independent pool marginals)   (reference S_null, D_MAX)

Everything derives from PARAMS + meta ablations + a FIXED observational pool
(POOL_SEED) at the cheap source's regime (config={}, mix_logit=0). Closed-form
moments only -- re-running must reproduce the committed fixtures byte-for-byte.

lambda_mdl is NOT recalibrated here: v1 has no battery yet (the calibration grid
is pre-registered separately, Decision Log v0.31); meta's lambda stays provisional.

Run:  .venv/Scripts/python cases/mendel_subtypes_v1/make_ladder_fixtures.py
"""

import sys
from pathlib import Path
from types import SimpleNamespace

import numpy as np

CASE_DIR = Path(__file__).parent
sys.path.insert(0, str(CASE_DIR))

import world  # noqa: E402  (factory side; the agent never sees this)

POOL_SEED = 20260702
POOL_N = 20000
PERTURB = 1.15  # fixed multiplier on the four structural coefficients (rung 2)
TWIN_REFIT_SEED = 90001  # rival_twin's deterministic moment-refit draw

P = world.PARAMS
ABL_CONFOUNDING = {"class_coef_dose": 0.0}   # from meta.json operators[confounding_por_clase]
ABL_HETEROGENEITY = {"slope_b": 1.5}         # from meta.json operators[heterogeneidad_latente]


def observational_pool():
    regime = SimpleNamespace(config={}, context={"mix_logit": 0.0}, horizon=None)
    return world.sample(regime, POOL_N, POOL_SEED)


def fit_numbers(pool):
    data = np.column_stack([pool[c].to_numpy() for c in world.COLUMNS])
    mu = data.mean(axis=0)
    cov = np.cov(data, rowvar=False)

    # machinery (b) refit for the confounding twin (mirrors rival_twin: the twin
    # 'didn't see the trap' and refits free params so its observational marginals
    # match the corrupted pool). For v1 the effect_dose leg is inert (no such key);
    # the active leg is the dose_base shift.
    p_twin = dict(P)
    p_twin.update(ABL_CONFOUNDING)
    obs = SimpleNamespace(config={}, context={"mix_logit": 0.0}, horizon=None)
    sim = world.mechanism(p_twin, obs, POOL_N, TWIN_REFIT_SEED)
    twin_dose_base = P["dose_base"] + float(pool["dose"].mean() - sim["dose"].mean())

    return {
        "mu": [float(v) for v in mu],
        "cov": [[float(v) for v in row] for row in cov],
        "marg": {
            c: (float(pool[c].mean()), float(pool[c].std())) for c in world.COLUMNS
        },
        "twin_dose_base": twin_dose_base,
    }


HEADER = (
    "GENERATED by make_ladder_fixtures.py (POOL_SEED={seed}, POOL_N={n}) - do not\n"
    "hand-edit; regenerate to audit. If an ordering fails, the default is to\n"
    "INVESTIGATE, never to retune (Decision Log v0.11)."
).format(seed=POOL_SEED, n=POOL_N)


def _mechanism_code(params: dict) -> str:
    """Self-contained model() with the given params baked in -- same generative
    code path as world.mechanism, so a fixture differs from the truth ONLY in
    its parameter values (never in code structure)."""
    return f'''import numpy as np
import pandas as pd

PARAMS = {params!r}
DOSE_MIN, DOSE_MAX = 0.0, 10.0


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    mix_logit = float(regime.context.get("mix_logit", 0.0))
    z = rng.binomial(1, _sigmoid(mix_logit), n).astype(float)

    marker = p["marker_sep"] * z + rng.normal(0.0, p["marker_noise"], n)

    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = p["dose_base"] + p["class_coef_dose"] * z + rng.normal(0.0, p["dose_noise"], n)
        dose = np.clip(raw, DOSE_MIN, DOSE_MAX)

    effect = np.where(z > 0.5, p["slope_b"], p["slope_a"])
    outcome = effect * dose + rng.normal(0.0, p["outcome_noise"], n)

    return pd.DataFrame({{"dose": dose, "marker": marker, "outcome": outcome}})
'''


def rung_2():
    p = dict(P)
    for k in ("marker_sep", "slope_a", "slope_b", "class_coef_dose"):
        p[k] = round(p[k] * PERTURB, 12)
    return f'''"""Rung 2 - truth with the four structural coefficients perturbed x{PERTURB}.

RATIONALE (rung 1 -> 2): a fixed 15% proportional error on grade separation,
both input slopes and the assignment strength produces a small but SYSTEMATIC
mismatch in every regime - in-support, out-of-record and observational alike -
while keeping every mechanism pathway intact (two grades, opposite signs,
confounded assignment). Expected strictly below the exact truth (whose only
mismatch is sampling noise) and above rungs that remove structure rather than
miscalibrate it.

{HEADER}
"""
''' + _mechanism_code(p)


def rung_3():
    p = dict(P)
    p.update(ABL_CONFOUNDING)
    return f'''"""Rung 3 - confounding_por_clase ablated (class_coef_dose=0), NO refit.

The visibility rung of the confounding operator (gate (ii) of the c_F sweep,
Decision Log v0.31): the world where the input assignment never depended on the
grade. Under do(dose) it is EXACT (the ablated pathway is exactly the one do()
replaces) - all of its loss is concentrated in the OBSERVATIONAL items, where
its dose marginal is wrong (mean {P["dose_base"]!r} vs the confounded pool) and the
grade-input dependence is absent.

RATIONALE (rung 2 -> 3): rung 2 is mildly wrong EVERYWHERE; this rung is exactly
right on interventional items and structurally wrong on the observational quota.
No total order between them is guaranteed by construction (monotonia-por-eje,
ARCHITECTURE 13-L1): what IS required is losing >=3xCV vs truth under the
combined score - energy already sees a shifted dose marginal, so this operator's
visibility should NOT need the functional (the sharp-baseline expectation:
confounding-passes at c_F=0).

{HEADER}
"""
''' + _mechanism_code(p)


def rung_4(f):
    p = dict(P)
    p.update(ABL_CONFOUNDING)
    p["dose_base"] = f["twin_dose_base"]
    return f'''"""Rung 4 - innocent twin of confounding (machinery (b): ablation + refit).

Rival recipe (b) as build_standard_rivals derives it: operator removed AND free
params refit so the observational marginals match the corrupted pool - here the
dose_base absorbs the confounded pool's dose mean ({f["twin_dose_base"]!r} vs the
truth's {P["dose_base"]!r}). It believes the historical input levels were just
'how the line runs', not grade-driven.

RATIONALE (rung 3 -> 4): the twin REPAIRS the dose marginal that rung 3 gets
wrong (its observational dose mean now matches the pool) but the repair is a
LIE: dose is shifted for every unit instead of for the type-B units, so the
grade-input dependence (and with it the marker-dose and outcome-dose joints)
is still wrong, and under do() it now runs a MIScalibrated assignment center
in observational-context predictions. The pair (3, 4) prices exactly what the
refit buys and what it cannot buy. For v1 the heterogeneity twin degenerates
to its pure ablation (the slope ablation does not touch the dose process ->
refit shift ~= 0; effect_dose leg inert) and is omitted as a duplicate
(Decision Log v0.33 addendum).

{HEADER}
"""
''' + _mechanism_code(p)


def rung_5():
    p = dict(P)
    p.update(ABL_HETEROGENEITY)
    return f'''"""Rung 5 - heterogeneidad_latente ablated (slope_b=+{ABL_HETEROGENEITY["slope_b"]!r}), NO refit.

The visibility rung of the heterogeneity operator (gate (ii), the PRIMARY gate
of the c_F sweep): the homogeneous world where both grades respond with the
type-A slope. No sign flip -> no bimodal outcome under do(), no opposite tails,
no scrap mass where the truth has it.

RATIONALE (rung 4 -> 5): rungs 3-4 keep the heterogeneity and break assignment;
this rung keeps assignment and removes the heterogeneity itself - the structure
the case exists to reward. Note its moments are NOT matched to the truth (a
pure ablation shifts the outcome mean, which marginal energy distance does
see); the moment-matched competitor whose failure isolates what energy CANNOT
see is rung 6. Where the sharp c_F=0 baseline (heterogeneity-fails) actually
bites - this rung, rung 6, or both - is an empirical question the sweep's
baseline report answers per rung (Decision Log v0.31 (a)).

{HEADER}
"""
''' + _mechanism_code(p)


def rung_6():
    return f'''"""Rung 6 - moment-matched Gaussian oracle (DIAGNOSTIC rung, unimodal).

The strongest no-multimodality competitor: a Gaussian with the EXACT per-regime
mean and covariance of the truth, computed in closed form from PARAMS (mixture
moment algebra; the observational branch ignores dose clipping - declared
approximation, clip is ~4 sigma out at mix_logit=0). It fits any mean, variance
and heteroscedasticity perfectly; what it CANNOT represent is the two-cluster
joint. Under energy-alone it scored R=0.96 on Latent v0 (Decision Log v0.25) -
the blind spot the combined score exists to close.

RATIONALE (position): this rung is DIAGNOSTIC ("does the meter see?"), not a
degradation on any single axis: it answers gate (iii) - oracle strictly below
world.py by >=3xCV under the combined score - and has NO required rank among
the intermediate rungs (v0.31: where it lands is reported as data, never
gated). It operationalizes the Visibility certificate (ARCHITECTURE 7/13-L1).

{HEADER}
"""
import numpy as np
import pandas as pd

PARAMS = {dict(P)!r}
DOSE_MIN, DOSE_MAX = 0.0, 10.0


def _sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def _mixture_moments(p_b, means, covs):
    """Exact mean/cov of a 2-component Gaussian mixture (weights 1-p_b, p_b)."""
    w = np.array([1.0 - p_b, p_b])
    m = w[0] * means[0] + w[1] * means[1]
    s = sum(
        w[k] * (covs[k] + np.outer(means[k] - m, means[k] - m)) for k in (0, 1)
    )
    return m, s


def model(regime, n, seed):
    p = PARAMS
    rng = np.random.default_rng(seed)
    p_b = _sigmoid(float(regime.context.get("mix_logit", 0.0)))
    on2 = p["outcome_noise"] ** 2
    mn2 = p["marker_noise"] ** 2

    if "dose" in regime.config:
        d = float(regime.config["dose"])
        # per grade z: (marker, outcome) independent Gaussians at fixed dose
        means = [
            np.array([0.0, p["slope_a"] * d]),
            np.array([p["marker_sep"], p["slope_b"] * d]),
        ]
        covs = [np.diag([mn2, on2]), np.diag([mn2, on2])]
        m, s = _mixture_moments(p_b, means, covs)
        draw = rng.multivariate_normal(m, s, n)
        return pd.DataFrame(
            {{"dose": np.full(n, d), "marker": draw[:, 0], "outcome": draw[:, 1]}}
        )

    # observational: per grade z, (dose, marker, outcome) is Gaussian with
    # dose ~ N(base + coef*z, dn2), outcome = slope_z*dose + eps
    dn2 = p["dose_noise"] ** 2
    means, covs = [], []
    for z, slope in ((0.0, p["slope_a"]), (1.0, p["slope_b"])):
        mu_d = p["dose_base"] + p["class_coef_dose"] * z
        means.append(np.array([mu_d, p["marker_sep"] * z, slope * mu_d]))
        covs.append(
            np.array(
                [
                    [dn2, 0.0, slope * dn2],
                    [0.0, mn2, 0.0],
                    [slope * dn2, 0.0, slope**2 * dn2 + on2],
                ]
            )
        )
    m, s = _mixture_moments(p_b, means, covs)
    draw = rng.multivariate_normal(m, s, n)
    return pd.DataFrame(
        {{
            "dose": np.clip(draw[:, 0], DOSE_MIN, DOSE_MAX),
            "marker": draw[:, 1],
            "outcome": draw[:, 2],
        }}
    )
'''


def rung_7(f):
    return f'''"""Rung 7 - naive generative fit: joint Gaussian of the corrupted pool.

Rival recipe (a), the S_naive anchor (R=0): "the data says what it seems to
say". A joint Gaussian of the single-composition observational pool, used
generatively; under do(dose) it samples (marker, outcome) from the
OBSERVATIONAL conditional given that dose.

RATIONALE (rung 6 -> 7): rung 6 gets every regime's first two moments exactly
right and fails only on shape; this rung's moments are frozen at the historical
composition and dragged through the observational conditional - under do() it
keeps the indication pattern randomization falsifies, and under composition
shifts (the out-of-record band) it does not move at all. It is the calibrated
"believe the record" floor of the normalization.

RATIONALE (rung 7 -> 8): see rung 8.

{HEADER}
"""
import numpy as np
import pandas as pd

MU = np.array({f["mu"]!r})
COV = np.array({f["cov"]!r})


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "dose" in regime.config:
        d = float(regime.config["dose"])
        mu_c = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_c = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_c, cov_c, n)
        return pd.DataFrame(
            {{"dose": np.full(n, d), "marker": draw[:, 0], "outcome": draw[:, 1]}}
        )
    draw = rng.multivariate_normal(MU, COV, n)
    return pd.DataFrame(
        {{
            "dose": np.clip(draw[:, 0], 0.0, 10.0),
            "marker": draw[:, 1],
            "outcome": draw[:, 2],
        }}
    )
'''


def rung_8(f):
    marg = f["marg"]
    return f'''"""Rung 8 - null model: independent marginals of the observational pool.

RATIONALE (rung 7 -> 8): the null keeps only the historical marginals - it
destroys every dependency between columns AND every sensitivity to the regime
(under do(dose) it still samples dose from the pool marginal: the implicit
no-effect claim, priced on every item). Any fit to real data beats it on joint
structure; it is the "I know nothing" floor that anchors S_null, the D_MAX cap
and the crash semantics (crash pays strictly worse than this).

{HEADER}
"""
import numpy as np
import pandas as pd

MARG = {marg!r}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {{}}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, 0.0, 10.0) if c == "dose" else v
    return pd.DataFrame(out)
'''


def write_fixtures(numbers) -> None:
    ladder_dir = CASE_DIR / "ladder"
    ladder_dir.mkdir(exist_ok=True)
    fixtures = {
        "rung_2_perturbed.py": rung_2(),
        "rung_3_ablate_confounding.py": rung_3(),
        "rung_4_twin_confounding.py": rung_4(numbers),
        "rung_5_ablate_heterogeneity.py": rung_5(),
        "rung_6_oracle_moments.py": rung_6(),
        "rung_7_naive_fit.py": rung_7(numbers),
        "rung_8_null.py": rung_8(numbers),
    }
    for name, content in fixtures.items():
        (ladder_dir / name).write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote ladder/{name}")


if __name__ == "__main__":
    pool = observational_pool()
    numbers = fit_numbers(pool)
    write_fixtures(numbers)
    print("done: 7 fixtures (rungs 2-8); rung 1 is world.py itself (run_ladder).")
