"""Null model (S_null / D_MAX reference): independent marginals of the record.

GENERATED by make_ladder_fixtures.py (ROUTED pool, POOL_SEED=50001, POOL_N=4000)
- do not hand-edit; regenerate to audit.
"""
import numpy as np
import pandas as pd

MARG = {'driver': (5.015103976722816, 2.894077333643766), 'signal': (4.9353389181388705, 2.444016421578156), 'outcome': (6.922607736726748, 3.875903677812206), 'ambient': (0.016200951069419274, 1.0114056603981707)}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, 0.0, 10.0) if c == "driver" else v
    return pd.DataFrame(out)
