"""Rung 8 -- null model: independent record marginals (S_null / D_MAX reference).

GENERATED by make_ladder_fixtures.py (POOL_SEED=50001, POOL_N=4000) - do not hand-edit.
"""
import numpy as np
import pandas as pd

MARG = {'driver': (4.563327518098527, 1.2006305197565874), 'signal': (-0.013583500331767919, 1.7976260632469752), 'outcome': (26.925252867420568, 5.845429586512766)}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    out = {}
    for c, (mu, sd) in MARG.items():
        v = rng.normal(mu, sd, n)
        out[c] = np.clip(v, 0.0, 10.0) if c == "driver" else v
    return pd.DataFrame(out)
