"""Rung 8 -- null: yield collapsed to its pooled mean, no spread
(S_null / D_MAX reference; the envelope is priced, so this is off-support).
GENERATED by build_and_certify.py (POOL_SEED=50001) - do not hand-edit."""
import numpy as np
import pandas as pd


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    return pd.DataFrame({"gas_yield": rng.normal(21.57666173475082, 0.01, n)})
